### ISSUE TITLE
ERROR Error: Uncaught (in promise): ReferenceError: Spinner is not defined ReferenceError: Spinner is not defined

### ISSUE THREAD

**Issue by Waldspecht** [seanlmcgill/ng2spin#1]
Hi,
i'm trying to build a component based on your example.
But I always get the message: ERROR Error: Uncaught (in promise): ReferenceError: Spinner is not defined
ReferenceError: Spinner is not defined

I guess it has to do with this declaration not being availble:
declare var Spinner: any;

Any Idea?

**Comment by Waldspecht** [comment]
Okay, I've got it. 
You have to reference the spin.js file correctly, so it finds the global Spinner variable.

After doing that everything works perfectly.
Thx for the example, and good work.

**Comment by seanlmcgill** [comment]
Hey, just saw your message, sorry I didn't get back to your earlier - glad things are working for you now though.  I should probably update this as I originally did it way back when Angular 2 was in beta.

Sean

**Comment by bigN13** [comment]
For anyone who experience the same issue to solve it you will have to include the spin.js in the angular_cli file.

**Comment by Waldspecht** [comment]
It's been a while but let me try to remember it right:

I needed to go to http://spin.js.org/ and fetch the spin.min.js file and include it in my project and reference it in the index.html file.
<script src="~/assets/js/spin.min.js"></script>

Then it worked for me. Hope that helps.

**Comment by bigN13** [comment]
i have tried that but it didn't worked in angular 4 ... however if you just include it in the angular_cli then it start working straight away

**Comment by seanlmcgill** [comment]
Updated it for Angular 4 & CLI in case anyone cares at this point. hehe
